#Greenfoot properties. Settings in this file override "bluej.defs" and "greenfoot.defs"
#Wed May 20 16:49:17 BST 2026
bluej.debugger.x=16
bluej.debugger.y=16
bluej.editor.fontsize=12
bluej.editor.stride.sidebarShowing=true
bluej.openPackage1=C\:\\Users\\Shalom2\\Intro
bluej.projectPath=C\:\\Users\\Shalom2
bluej.recentProject0=C\:\\Users\\Shalom2\\Intro
bluej.terminal.dividerpos=500517
bluej.terminal.height=838
bluej.terminal.width=1550
bluej.terminal.x=0
bluej.terminal.y=0
greenfoot.uid=8e296d9a-79f5-4a32-96c6-aa434c02bc9a
session.numeditors.java=0
session.numeditors.stride=0
